### ISSUE TITLE
PR rejection reason (pilot round)

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/pull-request-analysis#2]
Let's do a 'pilot round', especially to onboard @siriwans 

Once we select a project (see #1 ), @tanayg could you please select 10 rejected PRs in the project and split into two subsets (five PRs go to Siri and the other five you take)?

Then you schedule a meeting to discuss your classifications. How does it sound? My suggestion is that you do this no later than Tuesday.

**Comment by tanayg** [comment]
@bcdasilv, your suggestions sound good to me. I've added my recommendations for the projects in #1. We should do a zoom meeting so we can do some preliminary discussion and perform the pilot round if time permits. I can meet anytime after 11am on Tuesday and Thursday. Let me know what works for you guys!

**Comment by siriwans** [comment]
done!
