### ISSUE TITLE
Meeting to discuss the pilot round

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/pull-request-analysis#3]
This depends on #2 (no later than Tuesday?)

**Comment by tanayg** [comment]
We could make Thursdays at 11am our weekly meeting times since no one has class at that time. Does that work @bcdasilv @siriwans ?

**Comment by bcdasilv** [comment]
Yes, but this Thu in particular I'm busy in a meeting.

**Comment by bcdasilv** [comment]
I'm available this Tuesday at 11 or during my office hours 2-4pm

**Comment by siriwans** [comment]
I'm available for either of those times Tuesdays or Thursdays.

**Comment by siriwans** [comment]
done!
